version: "3.5"

services:
  news_parser:
    build:
      context: .
      dockerfile: Dockerfile_news_parser
    restart: always
    env_file:
      - environment
    volumes:
      - .:/home/logs/
    depends_on:
      - db_postgres

  news_api:
    build:
      context: .
      dockerfile: Dockerfile_news_api
    restart: always
    env_file:
      - environment
    ports:
      - 5000:5000
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:11
    restart: always
    env_file:
      - environment
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./db_postgres/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql